videozid/videozid/ViewModels/ImportExcelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace videozid.ViewModels
{
    /// <summary>
    /// Prezentacijski pogled za uvoz FerWeb ili Dhmz računa, sadrži status ispravnosti uvezenih podataka
    /// </summary>
    public class ImportExcelViewModel
    {

            /// <summary>
            /// Status koji obilježava da li je račun unesen ili ne
            /// </summary>
            public string Status { get; set; }

            /// <summary>
            /// Korisničko ime 
            /// </summary>
            public string KorisnickoIme { get; set; }

            /// <summary>
            /// Lozinka 
            /// </summary>
            public string Lozinka { get; set; }

            /// <summary>
            /// Broj dozvole za pristup serveru
            /// </summary>
            public int? DozvolaServer { get; set; }

            /// <summary>
            /// Korisnicko ime korisnika koji posjeduje račun
            /// </summary>
            public string Vlasnik { get; set; }

        
    }
}

videozid/videozid/Controllers/ImportExcelController.cs
using iTextSharp.text;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using videozid.Models;
using videozid.ViewModels;
using videozid.ViewModels.Api;

namespace videozid.Controllers
{
    public class ImportExcelController : Controller
    {
        private IHostingEnvironment _environment;
        private const string ExcelContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        private readonly RPPP15Context context;

        public ImportExcelController(RPPP15Context context, IHostingEnvironment environment)
        {
            this.context = context;
            _environment = environment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult IndexDhmz()
        {
            return View();
        }

        public IActionResult IndexKorisnici()
        {
            return View();
        }

        public IActionResult IndexUredaji()
        {
            return View();
        }

        public IActionResult IndexVideozidovi()
        {
            return View();
        }

        public IActionResult IndexPrezentacije()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ICollection<IFormFile> files)
        {

            var uploads = Path.Combine(_environment.WebRootPath, "uploads");
            List<ImportExcelViewModel> racuni = new List<ImportExcelViewModel>();
         
            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    FileInfo fileExcel = new FileInfo(Path.Combine(uploads, file.FileName));

                    try
                    {

                        using (ExcelPackage package = new ExcelPackage(fileExcel))
                        {
                            ExcelWorksheet worksheet = package.Workbook.Worksheets[1];
                            int rowCount = worksheet.Dimension.Rows;
                            int ColCount = worksheet.Dimension.Columns;

                            for (int row = 2; row <= rowCount; row++)
                            {
                                ImportExcelViewModel racun = new ImportExcelViewModel();
                                string ime, lozinka, vlasnik;
                                int? dozvola;
                                if(worksheet.Cells[row, 1].Value != null)
                                {
                                     ime = worksheet.Cells[row, 1].Value.ToString();
                                    racun.KorisnickoIme = ime;
                                }
                                else
                                {
                                    ime = null;
                                    racun.KorisnickoIme = null;
                                }
                                if (worksheet.Cells[row, 2].Value != null)
                                {
                                    lozinka = worksheet.Cells[row, 2].Value.ToString();
                                    racun.Lozinka = lozinka;
                                }
                                else
                                {
                                    lozinka = null;
                                    racun.Lozinka = null;
                                }
                                if (worksheet.Cells[row, 3].Value != null)
                                {
                                    dozvola = Int32.Parse(worksheet.Cells[row, 3].Value.ToString());
                                    racun.DozvolaServer = dozvola;
                                }
                                else
                                {
                                    racun.DozvolaServer = null;
                                    dozvola = null;
                                }
                                if (worksheet.Cells[row, 4].Value != null)
                                {
                                    vlasnik = worksheet.Cells[row, 4].Value.ToString();
                                    racun.Vlasnik = vlasnik;
                                }
                                else
                                {
                                    vlasnik = null;
                                    racun.Vlasnik = null;
                                }

                                FerWebAcc racunFer = null;
                                var prosloKorisnika = false;
                                try
                                {
                                    Korisnik vlasnikRacuna = null;
                                    vlasnikRacuna = await context.Korisnik.AsNoTracking().Where(k => k.KorisnickoIme.Equals(vlasnik))
                                                                .FirstOrDefaultAsync();

                                    racunFer = new FerWebAcc
                                    {
                                        DozvolaServer = dozvola,
                                        KorisnickoIme = ime,
                                        Lozinka = lozinka
                                        
                                    };
                                    Debug.WriteLine(lozinka);
                                    Debug.WriteLine(lozinka);
                                    Debug.WriteLine(lozinka);
                                    Debug.WriteLine(lozinka);
                                    Debug.WriteLine(lozinka);

                                    

                                    if (vlasnikRacuna.FerId != null)
                                    {
                                        //korisnik već ima račun
                                        throw new System.ArgumentException("Ma samo baci iznimku");

                                    }
                                    else
                                    {
                                        prosloKorisnika = true;
                                        context.FerWebAcc.Add(racunFer);
                                        context.SaveChanges();

                                        //spojiti korisnika s FerWeb računom
                                        var korisnik = context.Korisnik.Where(k => k.Id.Equals(vlasnikRacuna.Id)).First();


                                        korisnik.FerId = racunFer.Id;
                                        context.Update(korisnik);
                                        context.Update(racunFer);

                                        context.SaveChanges();

                                        //uspješno spremljen
                                        racun.Status = "DA";

                                    }

                                }
                                catch(Exception e)
                                {
                                    //nije uspješno spremljen, status spremiti u izlazi excel file
                                    racun.Status = "NE";
                                    if (prosloKorisnika)
                                    {
                                        context.FerWebAcc.Remove(racunFer);

                                    }


                                }
                                finally
                                {
                                  
                                        racuni.Add(racun);
                                    
                                    
                                }
                            }
                           
                        }
                    }
                    catch (Exception e)
                    {

                    }

                }

                byte[] content;
                using (ExcelPackage excel = new ExcelPackage())
                {
                    excel.Workbook.Properties.Title = "Status unosa FerWeb računa";
                    excel.Workbook.Properties.Author = "Autor";
                    var worksheet = excel.Workbook.Worksheets.Add("FerWeb računi");

                    //First add the headers
                    worksheet.Cells[1, 1].Value = "Uneseno:";
                    worksheet.Cells[1, 2].Value = "Korisničko ime";
                    worksheet.Cells[1, 3].Value = "Lozinka";
                    worksheet.Cells[1, 4].Value = "Dozvola server";
                    worksheet.Cells[1, 5].Value = "Pripada";

                    for (int i = 0; i < racuni.Count; i++)
                    {
                        worksheet.Cells[i + 2, 1].Value = racuni[i].Status;
                        worksheet.Cells[i + 2, 2].Value = racuni[i].KorisnickoIme;
                        worksheet.Cells[i + 2, 2].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                        worksheet.Cells[i + 2, 3].Value = racuni[i].Lozinka;
                        worksheet.Cells[i + 2, 4].Value = racuni[i].DozvolaServer;
                        worksheet.Cells[i + 2, 5].Value = racuni[i].Vlasnik;
                    }

                    worksheet.Cells[1, 1, racuni.Count + 1, 4].AutoFitColumns();

                    content = excel.GetAsByteArray();
                }
                return File(content, ExcelContentType, "FerWebAcc.xlsx");
            }
            return View();
        }

        public async Task<IActionResult> PredlozakPrezentacija()
        {
            byte[] content;
            using (ExcelPackage excel = new ExcelPackage())
            {

videozid/videozid/Views/ImportExcel/Index.cshtml
</br>
</br>
<strong>Uvoz FerWeb računa. Koristiti Microsoft Edge preglednik.</strong>
<form method="post" asp-action="Index" asp-controller="ImportExcel" enctype="multipart/form-data">
    <input type="file" name="files" multiple />
    <input type="submit" value="Uvoz" />
</form>

</br>
</br>
<strong>Za unos FerWeb računa poželjno je koristiti sljedeći predložak</strong>
<a class="btn btn-success" asp-controller="ImportExcel" asp-action="PredlozakFerWebAcc">Prezumi</a>
</br>
<strong>Primjer test datoteke za unos</strong>
<a class="btn btn-success" asp-controller="ImportExcel" asp-action="TestAcc">Prezumi</a>

</br></br>
<a class="btn btn-primary btn-sm" asp-controller="FerWebAcc" asp-action="ApiIndex">Povratak na popis FerWeb računa</a>

videozid/videozid/Views/ImportExcel/IndexDhmz.cshtml
</br>
</br>
<strong>Uvoz Dhmz računa. Koristiti Microsoft Edge preglednik.</strong>
<form method="post" asp-action="IndexDhmz" asp-controller="ImportExcel" enctype="multipart/form-data">
    <input type="file" name="files" multiple />
    <input type="submit" value="Uvoz" />
</form>

</br>
</br>
<strong>Za unos Dhmz računa poželjno je koristiti sljedeći predložak</strong>
<a class="btn btn-success" asp-controller="ImportExcel" asp-action="PredlozakDhmzAcc">Prezumi</a>
</br>
<strong>Primjer test datoteke za unos</strong>
<a class="btn btn-success" asp-controller="ImportExcel" asp-action="TestAcc">Prezumi</a>

</br></br>
<a class="btn btn-primary btn-sm" asp-controller="DhmzAcc" asp-action="ApiIndex">Povratak na popis DHMZ računa</a>

videozid/videozid/Views/ImportExcel/IndexKorisnici.cshtml
</br>
</br>
Uvoz korisnika
<form method="post" asp-action="IndexKorisnici" asp-controller="ImportExcel" enctype="multipart/form-data">
    <input type="file" name="files" multiple />
    <input type="submit" value="Uvoz" />
</form>

</br>
</br>
Za unos korisnika poželjno je koristiti sljedeći predložak
<a class="btn btn-success" asp-controller="ImportExcel" asp-action="PredlozakKorisnici">Prezumi</a>

videozid/videozid/Views/ImportExcel/IndexPrezentacije.cshtml
@{

    ViewData["Title"] = "Uvoz prezentacija";
}

<br /><br />
<p>Uvoz prezentacija. Koristiti Microsoft Edge browser.</p>
<form method="post" asp-action="IndexPrezentacije" asp-controller="ImportExcel" enctype="multipart/form-data">
    <input type="file" name="files" multiple />
    <input type="submit" value="Uvoz" />
</form>

<br /><br />
<p>Za unos prezentacija pozeljno je koristiti sljedeci predlozak</p>
<a class="btn btn-success" asp-controller="ImportExcel" asp-action="PredlozakPrezentacija">Preuzmi</a>

videozid/videozid/Views/ImportExcel/IndexUredaji.cshtml
@{

    ViewData["Title"] = "Uvoz uredaja";
}

<br /><br />
<p>Uvoz uredaja</p>
<form method="post" asp-action="IndexUredaji" asp-controller="ImportExcel" enctype="multipart/form-data">
    <input type="file" name="files" multiple />
    <input type="submit" value="Uvoz" />
</form>

<br /><br />
<p>Za unos uredaja pozeljno je koristiti sljedeci predlozak</p>
<a class="btn btn-success" asp-controller="ImportExcel" asp-action="PredlozakUredaji">Prezumi</a>

videozid/videozid/Views/ImportExcel/IndexVideozidovi.cshtml
@{

    ViewData["Title"] = "Uvoz videozidova";
}

<br /><br />
<p>Uvoz videozidova</p>
<form method="post" asp-action="IndexVideozidovi" asp-controller="ImportExcel" enctype="multipart/form-data">
    <input type="file" name="files" multiple />
    <input type="submit" value="Uvoz" />
</form>

<br /><br />
<p>Za unos videozidova pozeljno je koristiti sljedeci predlozak</p>
<a class="btn btn-success" asp-controller="ImportExcel" asp-action="PredlozakVideozidovi">Prezumi</a>