videozid/videozid/Models/TipServisa.cs
using System;
using System.Collections.Generic;

namespace videozid.Models
{
    public partial class TipServisa
    {
        public int Id { get; set; }
        public int IdServis { get; set; }
        public string Tip { get; set; }

        public virtual Servis IdServisNavigation { get; set; }
    }
}

videozid/videozid/Controllers/WebAPI/TipServisaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using videozid.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace videozid.Controllers.WebAPI
{
    [Route("api/[controller]")]
    public class TipServisaController : Controller
    {
        private readonly RPPP15Context _context;

        /// <summary>
        /// Kontroler za upravljanje tipvoima servisa.
        /// </summary>
        /// <param name="context">Kontekst za pristup bazi podataka</param>
        public TipServisaController(RPPP15Context context)
        {
            _context = context;
        }

        // GET: TipServisas
        /// <summary>
        /// Metoda koja dohvaca sve tipove servisa i vrati pogled Index.
        /// </summary>
        /// <returns>Pogled Index sa pripadajućim modelom</returns>
        [HttpGet]
        public async Task<IActionResult> GetTipoviServisa()
        {
            var rPPP15Context = _context.TipServisa.Include(t => t.IdServisNavigation);
            return View("IndexAPI", await rPPP15Context.ToListAsync());
        }

        /// <summary>
        /// Metoda koja odabire tip servisa za detaljniji pregled na temelju ID-a.
        /// </summary>
        /// <param name="id">id tipa servisa</param>
        /// <returns>Pogled Details sa odgovarajućim modelom</returns>
        [HttpGet("details/{id}", Name ="DetailsTip")]
        public async Task<IActionResult> GetDetails(int? id)
        {
            if (id == null)
            {
                TempData[Constants.Error] = "Vrijednost ID ne može biti null.";
                return RedirectToAction("Index");
            }

            var tipServisa = await _context.TipServisa
                .Include(t => t.IdServisNavigation)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (tipServisa == null)
            {
                TempData[Constants.Error] = "Tip servisa sa id=" + id + " ne postoji.";
                return RedirectToAction("Index");
            }

            return View("DetailsAPI",tipServisa);
        }

        /// <summary>
        /// Metoda koja odabire tip servisa za uredivanje na temelju ID-a.
        /// </summary>
        /// <param name="id">id tipa servisa</param>
        /// <returns>Pogled Edit sa odgovarajućim modelom</returns>>
        /// <returns></returns>
        [HttpGet("edit/{id}", Name = "EditTip")]
        public async Task<IActionResult> GetEdit(int? id)
        {
            if (id == null)
            {
                TempData[Constants.Error] = "Vrijednost ID ne može biti null.";
                return RedirectToAction("Index");
            }

            var tipServisa = await _context.TipServisa.SingleOrDefaultAsync(m => m.Id == id);
            if (tipServisa == null)
            {
                TempData[Constants.Error] = "Tip servisa sa id=" + id + " ne postoji.";
                return RedirectToAction("Index");
            }

            ViewData["IdServis"] = new SelectList(_context.Servis, "Id", "Ime", tipServisa.IdServis);
            return View("EditAPI",tipServisa);
        }


        /// <summary>
        /// Metoda koja sprema promjete u tipu servisa zadanom određenom s ID-om.
        /// </summary>
        /// <param name="id">id tipa</param>
        /// <param name="tipServisa">ime tipa</param>
        /// <returns>Pogled Post</returns>
        [HttpPost("edit/{id}", Name ="EditTipPost")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostEdit(int id, [FromBody] TipServisa tipServisa)
        {
            if (id != tipServisa.Id)
            {
                TempData[Constants.Error] = "ID-evi se ne poklapaju: " + id + "!=" + tipServisa.Id;
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipServisa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipServisaExists(tipServisa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                TempData["Success"] = "Tip servisa \"" + tipServisa.Tip + "\" uspiješno promjenjen.";

                return RedirectToAction("GetTipoviServisa");
            }

            ViewData["IdServis"] = new SelectList(_context.Servisira, "Id", "Id", tipServisa.IdServis);
            ViewData["IdServis"] = new SelectList(_context.Servis, "Id", "Ime", tipServisa.IdServis);

            TempData["Error"] = "Tip servisa \"" + tipServisa.Tip + "\" nije promjenjen.";

            return View(tipServisa);
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="id"> id tipa servisa</param>
        /// <returns>True ako tip servisa postoji u bazi podataka</returns>
        private bool TipServisaExists(int id)
        {
            return _context.TipServisa.Any(e => e.Id == id);
        }
    }
}

videozid/videozid/Views/TipServisa/Create.cshtml
@model videozid.Models.TipServisa

@{
    ViewData["Title"] = "Novi tip";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Novi tip servisa</title>
</head>
<body>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Tip Servisa</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="form-group">
            <label asp-for="IdServis" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="IdServis" class ="form-control" asp-items="ViewBag.IdServis"></select>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Tip" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Tip" class="form-control" required/>
                <span asp-validation-for="Tip" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

<div>
   <a class="btn btn-primary" asp-controller="TipServisa" asp-action="Index"> Tipovi servisa</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

videozid/videozid/Views/TipServisa/Details.cshtml
@model videozid.Models.TipServisa

@{
    ViewData["Title"] = "Tip servisa";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalji</title>
</head>
<body>

<div>
    <h4>Datelji - tip Servisa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tip)
        </dd>
        <dt>
            Ime servisa
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdServisNavigation.Ime)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Uredi</a>
    <a class="btn btn-primary" asp-action="Index">Tipovi servisa</a>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id">Obriši</a>
</div>
</body>
</html>

videozid/videozid/Views/TipServisa/DetailsAPI.cshtml
@model videozid.Models.TipServisa

@{
    ViewData["Title"] = "Tip servisa";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalji</title>

    <script>
        function changeWindow(action, id) {
            var url = "/api/tipservisa/"
            if (action != '') {
                url += action + "/";
            }

            if (id != '') {
                url += id;
            }

            window.location = url
        }
    </script>
</head>
<body>

<div>
    <h4>Datelji - tip Servisa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tip)
        </dd>
        <dt>
            Ime servisa
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdServisNavigation.Ime)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" onclick="changeWindow('edit',@Model.Id)">Uredi</a>
    <a class="btn btn-primary" onclick="changeWindow('','')">Tipovi servisa</a>
</div>
</body>
</html>

videozid/videozid/Views/TipServisa/Edit.cshtml
@model videozid.Models.TipServisa

@{
    ViewData["Title"] = "Uredi";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Uredi - Tip servisa</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="IdServis" class="control-label col-md-2">Servis</label>
            <div class="col-md-10">
                <select asp-for="IdServis" class="form-control" asp-items="ViewBag.IdServis"></select>
                <span asp-validation-for="IdServis" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Tip" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Tip" class="form-control" required/>
                <span asp-validation-for="Tip" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

<div>
    <a class="btn btn-primary"  asp-action="Index">Tipovi servisa</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

videozid/videozid/Views/TipServisa/EditAPI.cshtml
@model videozid.Models.TipServisa

@{
    ViewData["Title"] = "Uredi";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>

    <script>
        function changeWindow(action, id) {
            var url = "/api/tipservisa/"
            if (action != '') {
                url += action + "/";
            }

            if (id != '') {
                url += id;
            }

            window.location = url
        }
    </script>

</head>
<body>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Uredi - Tip servisa</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="IdServis" class="control-label col-md-2">Servis</label>
            <div class="col-md-10">
                <select asp-for="IdServis" class="form-control" asp-items="ViewBag.IdServis"></select>
                <span asp-validation-for="IdServis" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Tip" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Tip" class="form-control" required/>
                <span asp-validation-for="Tip" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

<div>
    <a class="btn btn-primary"  asp-action="Index">Tipovi servisa</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

videozid/videozid/Views/TipServisa/Index.cshtml
@model IEnumerable<videozid.Models.TipServisa>


@{
    ViewData["Title"] = "Tipovi servisa";
}
<!DOCTYPE html>
<meta charset="ISO-8859-1"> 

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Tip servisa</title>

    <script>

        function deleteRow(id) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("DeleteAsync", "TipServisa")",
                data: { id: id },
                ajaxasync: true,
                success: function (data) {
                    $('#tablica').DataTable()
                        .row(document.getElementById('row-'.concat(id)))
                        .remove()
                        .draw();
                },
                error: function (data) {
                    alert("Greška");
                }
            });
        }

    </script>

</head>
<body>

    <div class="row">
        <br /> <br />
        <h3>Tip servisa (Šifrarnik - jednostavan prikaz)</h3>
        <br />
    </div>

    <div class="row" id="tableDiv">
        @Html.Partial("TableView")
    </div>
       
    @*<div class="row">
        <p>
            <a class="btn btn-primary" asp-controller="TipServisa" asp-action="Create">Novi tip</a>
        </p>
    </div>*@
   
</body>
</html>

@section styles{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
}

@section scripts{
    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script>
  $(document).ready(function(){
      $('#tablica').DataTable();
  });
    </script>
}

videozid/videozid/Views/TipServisa/IndexAPI.cshtml
@model IEnumerable<videozid.Models.TipServisa>


@{
    ViewData["Title"] = "Tipovi servisa";
}
<!DOCTYPE html>
<meta charset="ISO-8859-1"> 

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Tip servisa</title>

    <script>
        function changeWindow(action, id) {
            var url = "/api/tipservisa/"
            if (action != '') {
                url += action + "/";
            }

            if (id != '') {
                url += id;
            }

            window.location = url
        }
    </script>
</head>
<body>

    <div class="row">
        <br /> <br />
        <h3>Tip servisa (Šifrarnik - jednostavan prikaz)</h3>
        <br />
    </div>

    <div class="row" id="tableDiv">
        @Html.Partial("TableViewAPI")
    </div>
   
</body>
</html>

@section styles{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
}

@section scripts{
    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script>
  $(document).ready(function(){
      $('#tablica').DataTable();
  });
    </script>
}

videozid/videozid/Views/TipServisa/TableView.cshtml
@model IEnumerable<videozid.Models.TipServisa>

<table class="table table-bordered table-striped text-center" id="tablica">

    <thead>
        <tr>
            <th>Tip servisa</th>
            <th>Ime servisa</th>
            <th>Akcije</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
                {
            <tr id="row-@Html.DisplayFor(modelItem => item.Id)">
                <td>
                    @Html.DisplayFor(modelItem => item.Tip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdServisNavigation.Ime)
                </td>
                <td>
                    <div class="btn-group" role="group">
                        <a class="btn btn-default btn-sm" asp-controller="TipServisa" asp-action="Edit" asp-route-id="@item.Id"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-info btn-sm" asp-controller="TipServisa" asp-action="Details" asp-route-id="@item.Id"><span class="glyphicon glyphicon-edit"></span></a>
                        @*<a class="btn btn-danger btn-sm" onclick="deleteRow(@item.Id)"><span class="glyphicon glyphicon-remove"></span></a>*@
                    </div>
                </td>
            </tr>
                }
    </tbody>
</table>

videozid/videozid/Views/TipServisa/TableViewAPI.cshtml
@model IEnumerable<videozid.Models.TipServisa>

<table class="table table-bordered table-striped text-center" id="tablica">

    <thead>
        <tr>
            <th>Tip servisa</th>
            <th>Ime servisa</th>
            <th>Akcije</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
                {
            <tr id="row-@Html.DisplayFor(modelItem => item.Id)">
                <td>
                    @Html.DisplayFor(modelItem => item.Tip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdServisNavigation.Ime)
                </td>
                <td>
                    <div class="btn-group" role="group">
                        <a class="btn btn-default btn-sm" onclick="changeWindow('edit',@item.Id)"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-info btn-sm" onclick="changeWindow('details',@item.Id)"><span class="glyphicon glyphicon-edit"></span></a>
                    </div>
                </td>
            </tr>
                }
    </tbody>
</table>