videozid/videozid/Models/EkranZida.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace videozid.Models
{
    /// <summary>
    /// Podatkovni model ekrana videozida
    /// </summary>
    public partial class EkranZida
    {
        /// <summary>
        /// ID ekrana videozida
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// ID ekrana videozida u tablici Uređaj
        /// </summary>
        public int IdUredaja { get; set; }

        /// <summary>
        /// Id videozida kojem pripada ovaj ekran
        /// </summary>
        public int IdZida { get; set; }

        /// <summary>
        /// X koordinata na kojoj se ekran zida nalazi
        /// </summary>
        [Range(0, 100)]
        public int XKoord { get; set; }

        /// <summary>
        /// Y koordinata na kojoj se ekran zida nalazi
        /// </summary>
        [Range(0, 100)]
        public int YKoord { get; set; }

        /// <summary>
        /// IdUredajaNavigation
        /// </summary>
        public virtual Uredaj IdUredajaNavigation { get; set; }

        /// <summary>
        /// IdZidaNavigation
        /// </summary>
        public virtual Videozid IdZidaNavigation { get; set; }
    }
}

videozid/videozid/Controllers/WebAPI/EkranZidaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using videozid.Models;
using videozid.ViewModels;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Net;
using videozid.ViewModels.Api;
using Microsoft.Extensions.Logging;

namespace videozid.Controllers.WebAPI
{

    /// <summary>
    /// Web API servis za rad s ekranima Videozida.
    /// </summary>
    [Route("api/[controller]/[action]")]
    public class EkranZidaController : Controller
    {
        private readonly RPPP15Context _context;
        private ILogger _logger;

        /// <summary>
        /// Konstruktor.
        /// </summary>
        /// <param name="context">RPPP15Context za pristup bazi podataka</param>
        /// /// <param name="logger">>Loger koji zapisuje u bazu podataka</param>
        public EkranZidaController(RPPP15Context context, ILogger<ServisController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: api/EkranZida
        /// <summary>
        /// Postupak za dohvat svih ekrana videozidova. 
        /// </summary>
        /// <returns>Popis svih ekrana sortiran po Id-u</returns>
        [HttpGet]
        [ActionName("GetAll")]
        [SwaggerResponseAttribute((int)HttpStatusCode.OK, typeof(IEnumerable<EkranZidaApiModel>), Description = "Vraća enumeraciju ekrana videozidova")]
        public async Task<IEnumerable<EkranZidaApiModel>> EkraniGet()
        {
            var list = await _context.EkranZida
                                .Include(e => e.IdUredajaNavigation)
                                .Include(e => e.IdZidaNavigation)
                                .Select(d => new EkranZidaApiModel
                                {
                                    Id = d.Id,
                                    IdUredaja = d.IdUredaja,
                                    Uredaj = d.IdUredajaNavigation.Naziv,
                                    IdZida = d.IdZida,
                                    Zid = d.IdZidaNavigation.Naziv,
                                    XKoord = d.XKoord,
                                    YKoord = d.YKoord
                                })
                                .ToListAsync();
            list.Sort((a, b) =>  a.Id > b.Id ? 0 : 1);
            return list;
        }

        // GET api/Ekran/ID
        /// <summary>
        /// Postupak za dohvat ekrana čiji je ID jednak poslanom parametru.
        /// </summary>
        /// <param name="IdEkrana">ID ekrana</param>
        /// <returns>objekt tipa EkranZidaApiModel ili NotFound ako ekran videozida s traženim Id-em ne postoji</returns>
        [HttpGet("{IdEkrana}", Name = "DohvatiEkran")]
        [ActionName("Get")]
        [ProducesResponseType(typeof(EkranZidaApiModel), (int)HttpStatusCode.OK)]
        [ProducesResponseType((int)HttpStatusCode.NotFound)]
        public async Task<IActionResult> EkranGet(int IdEkrana)
        {
            var ekran = await _context.EkranZida
                                        .AsNoTracking()
                                        .Where(u => u.Id == IdEkrana)
                                        .FirstOrDefaultAsync();

            if (ekran == null)
            {
                _logger.LogWarning("Ekran videozida s navedenim ID-em ne postoji.");
                return NotFound("Ekran videozida s navedenim ID-em ne postoji.");
            }
            else
            {
                var model = new EkranZidaApiModel
                {
                    Id = ekran.Id,
                    IdUredaja = ekran.IdUredaja,
                    IdZida = ekran.IdZida,
                    XKoord = ekran.XKoord,
                    YKoord = ekran.YKoord
                };

                return new ObjectResult(model);
            }
        }

        // GET: api/Ekran/IDZida
        /// <summary>
        /// Postupak za dohvat svih ekrana jednog videozida. 
        /// </summary>
        /// <returns>Popis svih ekrana sortiran po Id-u</returns>
        [HttpGet("{IdZida}", Name = "DohvatiEkraneZida")]
        [ActionName("GetForWall")]
        [ProducesResponseType(typeof(IEnumerable<EkranZidaApiModel>), (int)HttpStatusCode.OK)]
        [ProducesResponseType((int)HttpStatusCode.NotFound)]
        public async Task<IActionResult> EkraniZidaGet(int IdZida)
        {
            var zid = await _context.Videozid
                                        .AsNoTracking()
                                        .Where(u => u.Id == IdZida)
                                        .FirstOrDefaultAsync();

            if (zid == null)
            {
                _logger.LogWarning("Videozid s navedenim ID-em ne postoji.");
                return NotFound("Videozid s navedenim ID-em ne postoji.");
            }
            else
            {
                var list = await _context.EkranZida
                                .Where(e => e.IdZida == IdZida)
                                .Select(d => new EkranZidaApiModel
                                {
                                    Id = d.Id,
                                    IdUredaja = d.IdUredaja,
                                    IdZida = d.IdZida,
                                    XKoord = d.XKoord,
                                    YKoord = d.YKoord
                                })
                                .ToListAsync();
                list.Sort((a, b) => a.Id > b.Id ? 0 : 1);
                return new ObjectResult(list);
            }
        }

        // POST api/Ekran
        /// <summary>
        /// Postupak kojim se unosi novi ekran videozida.
        /// </summary>
        /// <param name="ekran">Podaci o novom ekranu</param>
        /// <returns>201 ako je ekran videozida uspješno pohranjen, te se ujedno vraća i spremljeni objekt, 400 u slučaju neispravnog modela</returns>
        [HttpPost]
        [ActionName("New")]
        [ProducesResponseType((int)HttpStatusCode.Created)]
        [ProducesResponseType((int)HttpStatusCode.BadRequest)]
        public async Task<IActionResult> EkranCreate([FromBody] EkranZida ekran)
        {
            if (ekran.XKoord < 0 || ekran.YKoord < 0)
            {
                _logger.LogWarning("Neispravne koordinate!");
                return BadRequest("Neispravne koordinate!");
            }

            else if (await _context.Uredaj.FindAsync(ekran.IdUredaja) == null)
            {
                _logger.LogWarning("Uređaj s navedenim ID-em (" + ekran.IdUredaja + ") ne postoji.");
                return NotFound("Uređaj s navedenim ID-em (" + ekran.IdUredaja + ") ne postoji.");
            }

            else if (await _context.Videozid.FindAsync(ekran.IdZida) == null)
            {
                _logger.LogWarning("Videozid s navedenim ID-em (" + ekran.IdZida + ") ne postoji.");
                return NotFound("Videozid s navedenim ID-em (" + ekran.IdZida + ") ne postoji.");
            }

            else if (await _context.EkranZida.Where(ek => ek.IdUredaja == ekran.IdUredaja && ek.IdZida == ekran.IdZida).FirstOrDefaultAsync() != null)
            {
                _logger.LogWarning("Videozid već sadrži navedeni ekran!");
                return BadRequest("Videozid već sadrži navedeni ekran!");
            }

            else if (await _context.EkranZida.Where(ek => ek.IdUredaja == ekran.IdUredaja && ek.IdZida == ekran.IdZida).FirstOrDefaultAsync() != null)
            {
                _logger.LogWarning("Neki videozid već sadrži navedeni ekran!");
                return BadRequest("Neki videozid već sadrži navedeni ekran!");
            }

            else if (await _context.EkranZida.Where(ek => ek.XKoord == ekran.XKoord && ek.YKoord == ekran.YKoord && ek.IdZida == ekran.IdZida).FirstOrDefaultAsync() != null)
            {
                _logger.LogWarning("Videozid već sadrži ekran na navedenim koordinatama!");
                return BadRequest("Videozid već sadrži ekran na navedenim koordinatama!");
            }

            else
            {
                var zid = await _context.Videozid.FindAsync(ekran.IdZida);

                if (ekran.XKoord >= zid.Sirina || ekran.YKoord >= zid.Visina)
                {
                    _logger.LogWarning("Neispravne koordinate!");
                    return BadRequest("Neispravne koordinate!");
                }

                _context.Add(ekran);
                await _context.SaveChangesAsync();

                var ek = _context.EkranZida.Where(e => e.IdUredaja == ekran.IdUredaja && e.IdZida == ekran.IdZida).Include(e => e.IdUredajaNavigation).First();
                _logger.LogInformation("Stvoren ekran zida ID = " + ek.Id);
                return new ObjectResult(new
                {
                    IdVeze = ek.Id,
                    Id = ek.IdUredaja,
                    Name = ek.IdUredajaNavigation.Naziv + "(" + ek.XKoord + "," + ek.YKoord + ")",
                });
            }
        }

        // PUT api/Ekran
        /// <summary>
        /// Ažurira ekran videozida s ID-em IdEkrana temeljem parametera iz zahtjeva.
        /// </summary>
        /// <param name="model">model s podacima o ekranu zida</param>
        /// <returns>204 ako je ekran videozida uspješno ažuriran, NotFound ako ekran s traženom šifrom ne postoji ili BadRequest ako model nije ispravan</returns>
        [HttpPut]
        [ActionName("Update")]
        [ProducesResponseType((int)HttpStatusCode.NotFound)]
        [ProducesResponseType((int)HttpStatusCode.NoContent)]
        [ProducesResponseType((int)HttpStatusCode.BadRequest)]
        public async Task<IActionResult> EkranUpdate([FromBody] EkranZidaApiModel model)
        {
            if (model == null || !ModelState.IsValid)
            {
                _logger.LogWarning(ModelState.ToString());
                return BadRequest(ModelState);

videozid/videozid/Views/EkranZida/Create.cshtml
@model videozid.Models.EkranZida

@{

    ViewData["Title"] = "Popis Ekrana";
}

<form asp-action="Create">
    <div class="form-horizontal">
        <br />
        <h4>EkranZida</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="IdUredaja" class="col-md-2 control-label">Ekran</label>
            <div class="col-md-10">
                <select asp-for="IdUredaja" class ="form-control" asp-items="ViewBag.IdUredaja"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IdZida" class="col-md-2 control-label">Videozid</label>
            <div class="col-md-10">
                <select asp-for="IdZida" class ="form-control" asp-items="ViewBag.IdZida"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="XKoord" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="XKoord" class="form-control" />
                <span asp-validation-for="XKoord" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="YKoord" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="YKoord" class="form-control" />
                <span asp-validation-for="YKoord" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj novi ekran" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

<div>
    <a class="btn btn-primary" asp-action="Index">Natrag na popis</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

videozid/videozid/Views/EkranZida/Delete.cshtml
@model videozid.Models.EkranZida

@{

    ViewData["Title"] = "Popis Ekrana";
}


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EkranZida</h4>
    <hr />
    <dl class="dl-horizontal col-md-offset-1">
        <input type="hidden" asp-for="Id" />
        <dt> XKoord</dt>
        <dd> @Model.XKoord</dd>

        <dt> YKoord</dt>
        <dd> @Model.YKoord</dd>

        <dt> Naziv Uredaja</dt>
        <dd> @Model.IdUredajaNavigation.Naziv</dd>

        <dt> Naziv Videozida</dt>
        <dd> @Model.IdZidaNavigation.Naziv</dd>
    </dl>
</div>
<div>
    <form asp-action="Delete">
        <div class="form-actions no-color btn-group" role="group">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a class="btn btn-primary" asp-action="Index">Natrag na popis</a>
        </div>
    </form>
</div>

videozid/videozid/Views/EkranZida/Details.cshtml
@model videozid.Models.EkranZida

@{

    ViewData["Title"] = "Popis Ekrana";
}

<!DOCTYPE html>

<div>
    <h4>EkranZida</h4>
    <hr />
    <dl class="dl-horizontal well">
        <dt> XKoord</dt>
        <dd> @Model.XKoord</dd>

        <dt> YKoord</dt>
        <dd> @Model.YKoord</dd>

        <dt> Naziv Uredaja</dt>
        <dd> @Model.IdUredajaNavigation.Naziv</dd>

        <dt> Naziv Videozida</dt>
        <dd> @Model.IdZidaNavigation.Naziv</dd>
    </dl>
</div>

<div class="row">
    <div class="btn-group" role="group">
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        <a class="btn btn-primary" asp-action="Index">Natrag na popis</a>
    </div>

    <div class="btn-group col-md-offset-1" role="group">
        <a class="btn btn-primary" asp-action="Previous" asp-route-id="@Model.Id">Prijasnji</a>
        <a class="btn btn-primary" asp-action="Next" asp-route-id="@Model.Id">Sljedeci</a>
    </div>
</div>

videozid/videozid/Views/EkranZida/Edit.cshtml
@model videozid.Models.EkranZida

@{

    ViewData["Title"] = "Popis Ekrana";
}
<!DOCTYPE html>


<form asp-action="Edit">
    <div class="form-horizontal well">
        <h4>EkranZida</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="IdUredaja" class="control-label col-md-2">Uredaj</label>
            <div class="col-md-10">
                <select asp-for="IdUredaja" class="form-control" asp-items="ViewBag.IdUredaja"></select>
                <span asp-validation-for="IdUredaja" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IdZida" class="control-label col-md-2">Videozid</label>
            <div class="col-md-10">
                <select asp-for="IdZida" class="form-control" asp-items="ViewBag.IdZida"></select>
                <span asp-validation-for="IdZida" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="XKoord" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="XKoord" class="form-control" />
                <span asp-validation-for="XKoord" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="YKoord" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="YKoord" class="form-control" />
                <span asp-validation-for="YKoord" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div class="btn-group">
    <a class="btn btn-primary" asp-action="Index">Natrag na popis</a>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id" OnClick="if(!confirm('Jeste li sigurni da zelite ukloniti @Model.IdUredajaNavigation.Naziv s videozida @Model.IdZidaNavigation.Naziv?')) return false;">Obrisi</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

videozid/videozid/Views/EkranZida/Index.cshtml
@model IEnumerable<videozid.Models.EkranZida>

@{

    ViewData["Title"] = "Popis Ekrana";
}

<p>
    <br /> <br />
    <a class="btn btn-primary" asp-action="Create">Dodaj novi ekran zida</a>
</p>
<div class="row">
    <br /> <br />
    <table class="table table-bordered table-striped text-center" id="tableEkrani">
        <thead>
            <tr>
                <th class="text-center"> Naziv Ekrana </th>
                <th class="text-center"> Naziv Videozida </th>
                <th class="text-center"> X - koord </th>
                <th class="text-center"> Y - koord </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="row-@item.Id">
                    <td> <b> <a asp-controller="Uredaj" asp-action="Details" asp-route-id="@item.IdUredaja"> @item.IdUredajaNavigation.Naziv </a></b> </td>
                    <td> <b> <a asp-controller="Videozid" asp-action="Details" asp-route-id="@item.IdZida"> @item.IdZidaNavigation.Naziv </a></b> </td>
                    <td> @item.XKoord</td>
                    <td> @item.YKoord</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a class="btn btn-default btn-sm" asp-action="Edit" asp-route-id="@item.Id"><span class="glyphicon glyphicon-pencil"></span></a>
                            <a class="btn btn-primary btn-sm" asp-action="Details" asp-route-id="@item.Id"><span class="glyphicon glyphicon-edit"></span></a>
                            <a class="btn btn-danger btn-sm" onclick="deleteEkran(@item.Id)"><span class="glyphicon glyphicon-remove"></span></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>



@section styles{
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
}

@section scripts{
    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tableEkrani').DataTable();
        });

        function deleteEkran(id) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("Delete", "EkranZida")",
                data: { id: id },
                ajaxasync: true,
                success: function (data) {
                    $('#tableEkrani').DataTable()
                        .row(document.getElementById('row-'.concat(id)))
                        .remove()
                        .draw();
                },
                error: function (data) {
                    alert("Greska");
                }
             });

        }
    </script>
}